// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zupcxxtnaglcappazciu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1cGN4eHRuYWdsY2FwcGF6Y2l1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUzNjc1ODIsImV4cCI6MjEwMDk0MzU4Mn0.Fwo4Td9ug5wEI_lfncT5XIPQMKe-k5atT1G3x7BkUd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});